export default {
    classNames: {
        SimpleTree: "simple-tree",
        SimpleTreeReadOnly: "simple-tree-readonly",
        SimpleTreeDropdownHolder: "simple-tree-dropdown-holder",
        SimpleTreeSingleSelectBox: "simple-tree-single-selectbox",
        SimpleTreeMultiSelectBox: "simple-tree-multi-selectbox",
        SimpleTreePillboxHolder: "simple-tree-pillbox-holder",
        SimpleTreePillboxCross: "simple-tree-pillbox-cross",
        SimpleTreeSelectedLabel: "simple-tree-selected-label",
        SimpleTreeSelectedLabelWatermark: "simple-tree-selected-label-watermark",
        SimpleTreeChevronUp: "simple-tree-chevron-up",
        SimpleTreeChevronDown: "simple-tree-chevron-down",
        SimpleTreeEmphasize: "simple-tree-emphasize-icon",
        SimpleTreeEmphasized: "simple-tree-emphasized",
        // Node classes
        SimpleTreeNodeContainer: "simple-tree-node-container",
        SimpleTreeNodeContainerRoot: "simple-tree-node-container-root",
        SimpleTreeNodeText: "simple-tree-node-text",
        SimpleTreeNodeBold: "simple-tree-node-bold",
        SimpleTreeNodeSelectable: "simple-tree-node-selectable",
        SimpleTreeNodeArrow: "simple-tree-node-arrow",
        SimpleTreeNodeWrapper: "simple-tree-node-wrapper",
        SimpleTreeNodeChevronContainer: "simple-tree-node-chevron-container",
        SimpleTreeNodeChevronClickable: "simple-tree-node-chevron-clickable",
        SimpleTreeNodeChevronDown: "simple-tree-node-chevron-down",
        SimpleTreeNodeChevronRight: "simple-tree-node-chevron-right",
    },
    nodeIdPrefix: "simple-tree-node",
};
