export default {
    classNames: {
        SimpleTree: "simple-tree",
        SimpleTreeReadOnly: "simple-tree-readonly",
        SimpleTreeViewOnly: "simple-tree-view-only",
        SimpleTreeDropdownHolder: "simple-tree-dropdown-holder",
        SimpleTreeSingleSelectBox: "simple-tree-single-selectbox",
        SimpleTreeMultiSelectBox: "simple-tree-multi-selectbox",
        SimpleTreeInputContainer: "simple-tree-input-container",
        SimpleTreePillboxHolder: "simple-tree-pillbox-holder",
        SimpleTreePillboxCross: "simple-tree-pillbox-cross",
        SimpleTreeCross: "simple-tree-cross",
        SimpleTreeClearable: "simple-tree-clearable",
        SimpleTreeSelectedLabel: "simple-tree-selected-label",
        SimpleTreeSelectedLabelWatermark: "simple-tree-selected-label-watermark",
        SimpleTreeChevronUp: "simple-tree-chevron-up",
        SimpleTreeChevronDown: "simple-tree-chevron-down",
        SimpleTreeEmphasize: "simple-tree-emphasize-icon",
        SimpleTreeEmphasized: "simple-tree-emphasized",
        // Node classes
        SimpleTreeNodeContainer: "simple-tree-node-container",
        SimpleTreeNodeContainerRoot: "simple-tree-node-container-root",
        SimpleTreeNodeText: "simple-tree-node-text",
        SimpleTreeNodeSelected: "simple-tree-node-selected",
        SimpleTreeNodeSelectable: "simple-tree-node-selectable",
        SimpleTreeNodeHovered: "simple-tree-node-hovered",
        SimpleTreeNodeArrow: "simple-tree-node-arrow",
        SimpleTreeNodeWrapper: "simple-tree-node-wrapper",
        SimpleTreeParentNode: "simple-tree-parent-node",
        SimpleTreeNodeChevronContainer: "simple-tree-node-chevron-container",
        SimpleTreeNodeChevronClickable: "simple-tree-node-chevron-clickable",
        SimpleTreeNodeChevronDown: "simple-tree-node-chevron-down",
        SimpleTreeNodeChevronRight: "simple-tree-node-chevron-right",
        SimpleTreeNodeCheckbox: "simple-tree-node-checkbox",
        SimpleTreeNodeCheckboxDisabled: "simple-tree-node-checkbox-disabled",
        SimpleTreeNodeCheckboxSelected: "simple-tree-node-checkbox-selected",
    },
    events: {
        SelectionChanged: "selectionChanged",
        SelectionChanging: "selectionChanging",
        NodeIndexChanged: "nodeIndexChanged",
        _NodeSelected: "_nodeSelected",
        EscapePressed: "_escapePressed",
        HoverChanged: "_hoverChanged",
        FilterChanged: "_filterChanged",
    },
    nodeIdPrefix: "simple-tree-node",
};
