import fs from "fs";
import path from "path";

const files = ["index.html", ".nojekyll"];
const ignoreFiles = ["_sidebar.md"];

// Directories generated by typedoc that contain API docs (entry point modules)
const apiModules = ["instance", "options", "rects", "subscription", "tree-node"];
// Subdirectory types within each module
const memberKinds = ["interfaces", "type-aliases", "functions"];

(async () => {
    const docsDir = __dirname;
    const outDir = path.join(__dirname, "out");
    const assetsDir = path.join(__dirname, "assets");
    const outAssetsDir = path.join(outDir, "assets");

    const filesInFolder = await fs.promises.readdir(docsDir);
    const mdFiles = filesInFolder.filter((f) => f.endsWith(".md") && !ignoreFiles.includes(f));

    await fs.promises.mkdir(outAssetsDir, { recursive: true });

    await Promise.all(files.map((f) => fs.promises.copyFile(`${docsDir}/${f}`, `${outDir}/${f}`)));
    await Promise.all(mdFiles.map((f) => fs.promises.copyFile(`${docsDir}/${f}`, `${outDir}/${f}`)));
    await Promise.all(
        (await fs.promises.readdir(assetsDir)).map((f) => fs.promises.copyFile(`${assetsDir}/${f}`, `${outAssetsDir}/${f}`))
    );

    // Generate Types sidebar from typedoc output
    const typesSidebar = await generateTypesSidebar(outDir);
    const generalSidebar = (await fs.promises.readFile(`${docsDir}/_sidebar.md`)).toString();
    const fullSidebar = generalSidebar + "\n" + typesSidebar;

    await fs.promises.writeFile(`${outDir}/_sidebar.md`, fullSidebar);

    console.log("Documentation copied successfully!");
})();

interface SidebarEntry {
    label: string;
    link: string;
}

async function generateTypesSidebar(outDir: string): Promise<string> {
    const lines: string[] = ["- Types Documentation"];

    for (const kind of memberKinds) {
        const entries: SidebarEntry[] = [];

        for (const mod of apiModules) {
            const kindDir = path.join(outDir, mod, kind);
            if (!fs.existsSync(kindDir)) {
                continue;
            }

            const files = await fs.promises.readdir(kindDir);
            for (const file of files) {
                if (!file.endsWith(".md")) {
                    continue;
                }

                const filePath = path.join(kindDir, file);
                const content = (await fs.promises.readFile(filePath)).toString();
                const title = extractTitle(content, file);
                const link = `${mod}/${kind}/${file}`;
                entries.push({ label: title, link });
            }
        }

        if (entries.length > 0) {
            const kindLabel = formatKindLabel(kind);
            lines.push(`  - ${kindLabel}`);
            for (const entry of entries) {
                lines.push(`    - [${entry.label}](${entry.link})`);
            }
        }
    }

    return lines.join("\n");
}

function extractTitle(content: string, fileName: string): string {
    // typedoc-plugin-markdown v4 uses breadcrumb format:
    // [Module](../README.md) / TypeName
    // The last segment after " / " on the breadcrumb line is the type name
    const breadcrumbLine = content.split("\n").find((line) => line.includes("] / "));
    if (breadcrumbLine) {
        const parts = breadcrumbLine.split(" / ");
        const lastPart = parts[parts.length - 1].trim();
        if (lastPart) {
            return lastPart;
        }
    }

    // Fallback: derive from filename
    return fileName.replace(".md", "");
}

function formatKindLabel(kind: string): string {
    switch (kind) {
        case "interfaces":
            return "Interfaces";
        case "type-aliases":
            return "Type Aliases";
        case "functions":
            return "Functions";
        default:
            return kind.charAt(0).toUpperCase() + kind.slice(1);
    }
}
