name: deploy-docs

on:
  workflow_dispatch: {}

permissions:
  actions: read
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ckotzbauer/actions-toolkit/setup-nodejs@fd699521fc995525d339964a82f6f781581bf471 # 0.57.0

      - name: Build
        run: |
          npm i
          npm run build:docs


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/out # The folder the action should deploy.