name: deploy-docs

on:
  workflow_dispatch: {}

permissions:
  actions: read
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ckotzbauer/actions-toolkit/setup-nodejs@187b42cc2ca9bc9257d6e72bb1c1be730f1d0565 # 0.56.0

      - name: Build
        run: |
          npm i
          npm run build:docs


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/out # The folder the action should deploy.