name: deploy-docs

on:
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: ckotzbauer/actions-toolkit/setup-nodejs@187b42cc2ca9bc9257d6e72bb1c1be730f1d0565 # 0.56.0

      - name: Build
        run: |
          npm i
          npm run build:docs

      - name: Install SSH Client
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          ssh-key: true
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/out # The folder the action should deploy.