name: build

on:
  push:
    branches:
      - '**'
  pull_request: {}

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@9e2a560f6c957fe29a2a78f8cbadabeea56a8c73 # 0.52.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build
      test-commands: npm test
      report-coverage: true
      coverage-file: ./coverage/lcov.info

  docs:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@9e2a560f6c957fe29a2a78f8cbadabeea56a8c73 # 0.52.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build:docs

  lint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@9e2a560f6c957fe29a2a78f8cbadabeea56a8c73 # 0.52.0
    with:
      install-node: true
      lint-commands: |
        npm ci
        npm run lint
