name: build

on:
  push:
    branches:
      - '**'
  pull_request: {}

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.43.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build
      test-commands: npm test
      report-coverage: true
      coverage-file: ./coverage/lcov.info

  docs:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@0.43.0
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build:docs

  lint:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-lint.yml@0.43.0
    with:
      install-node: true
      lint-commands: |
        npm ci
        npm run lint
